version: '2'
services:
  redis-master:
    image: redis:3.0-alpine
    ports:
      - "6379"

  redis-slave:
    image: redis:3.0-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    ports:
      - "6379"

  redis-sentinel:
    build:
      context: ./
    image: lamoda/redis-sentinel:latest
    ports:
      - "26379"

  redis-sentinel2:
    image: lamoda/redis-sentinel:latest
    depends_on:
      - redis-sentinel
    ports:
      - "26379"

  redis-sentinel3:
    image: lamoda/redis-sentinel:latest
    depends_on:
      - redis-sentinel
    ports:
      - "26379"
